filebeat.inputs:
  - type: log
    paths:
      - "/var/log/apache2/*.log"
    fields:
      apache: true

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]
  worker: 1

setup.ilm.enabled: true
setup.ilm.overwrite: true
